### ISSUE TITLE
maf files not build with GRCh38 version

### ISSUE THREAD

**Issue by luckyvivi** [SiYangming/TCGAmutations#1]
Hello Dr Yang,
I recently updated to the latest version of the TACGmutation package. However, when I attempted to load the MC3 COAD.RDs data, I noticed that it seems to be available only in the GRCh37 version. Is there a version available for GRCh38? If so, could you please guide me on how to access and load this data?

**Comment by SiYangming** [comment]
You can use UCSC's liftOver (https://genome.ucsc.edu/cgi-bin/hgLiftOver) tool to convert sites between GRCh37 and GRCh38

**Comment by luckyvivi** [comment]
> You can use UCSC's liftOver (https://genome.ucsc.edu/cgi-bin/hgLiftOver) tool to convert sites between GRCh37 and GRCh38



> You can use UCSC's liftOver (https://genome.ucsc.edu/cgi-bin/hgLiftOver) tool to convert sites between GRCh37 and GRCh38
您好，
感谢您的建议，但是我想确认一下，使用 liftOver 转换后，是否需要对 MAF 文件进行重新注释？

**Comment by SiYangming** [comment]
不需要
